// <auto-generated />
using System;
using ManagementAppCW02.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ManagementAppCW02.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20211218043912_AddCreatedDate")]
    partial class AddCreatedDate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ManagementAppCW02.Shared.Entities.CompanyEntity", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("companyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("companyType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("establishedDate")
                        .HasColumnType("Date");

                    b.Property<int>("numOfEmployees")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Companies");
                });
#pragma warning restore 612, 618
        }
    }
}
